[main]
font=IBM Plex Mono:size=13

[colors-dark]
alpha=0.95
foreground=ffe3c4
background=2a1a22
selection-foreground=2a1a22
selection-background=ff8f00

# Standard colors (dark palette)
regular0=22151a
regular1=ff5c3f
regular2=ffb85a
regular3=ffd178
regular4=ff9f45
regular5=c94c1d
regular6=ffcf99
regular7=ffe3c4

# Bright colors (light palette)
bright0=3a242f
bright1=ff7a5f
bright2=ffc778
bright3=ffe3a5
bright4=ffb36b
bright5=e0612c
bright6=ffddb3
bright7=fff1de
