[main]
font=IBM Plex Mono:size=13

[colors-dark]
alpha=0.92
foreground=ffffff
background=221d3f
selection-foreground=ffffff
selection-background=c95792

# Standard colors (dark palette)
regular0=3d365c
regular1=f8b55f
regular2=c95792
regular3=7c4585
regular4=5a4682
regular5=ecb56d
regular6=d99bc5
regular7=eef0ff

# Bright colors (light palette)
bright0=221d3f
bright1=ffe5c2
bright2=b29dd2
bright3=f8d590
bright4=c2b3ff
bright5=5a3b7d
bright6=9b6ab1
bright7=ffffff
