[main]
font=IBM Plex Mono:size=13

[colors-dark]
alpha=0.92
foreground=c7c4ff
background=1e1e3f
selection-foreground=ffffff
selection-background=4b4892

# Standard colors (dark palette)
regular0=1e1e3f
regular1=ff628c
regular2=a5ff90
regular3=fad000
regular4=91b4ff
regular5=b362ff
regular6=9effff
regular7=c7c4ff

# Bright colors (light palette)
bright0=2d2b55
bright1=ff7da3
bright2=b6ffad
bright3=ffe66d
bright4=a5c1ff
bright5=d18cff
bright6=b6ffff
bright7=ffffff
