[[profile]]
    name = "laptop-only"
    [[profile.output]]
    search = ["n=eDP-1", "m=0x0980", "v=BOE"]
    enable = true
    mode = "1920x1200"
    position = "0,0"
    scale = 1.0

[[profile]]
    name = "external-only"
    [[profile.output]]
    search = ["n=HDMI-A-1", "m=GM24H3G"]
    enable = true
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0

[[profile]]
    name = "hdmi-edp-mirror"
    [[profile.output]]
    search = ["n=HDMI-A-1", "m=GM24H3G"]
    enable = true
    mode = "1920x1080"
    position = "0,0"
    scale = 1.0

    [[profile.output]]
    search = ["n=eDP-1", "m=0x0980", "v=BOE"]
    enable = true
    # This panel currently only advertises 1920x1200/48-60Hz modes.
    mode = "1920x1080"
    position = "0,0"
    scale = 1.0
